### ISSUE TITLE
作者以后在空闲时候会用.net core重写一个么？？如有冒犯，无需回答

### ISSUE THREAD

**Issue by nieshuo** [oybab/TradingSystem#11]

**Comment by huangjinshe** [comment]
早就这么想了, 只是当时考虑到低版本操作系统兼容性没升级. 而且如果重写想升级的东西很多, 包括整个后端架构, 通讯协议. 不过目前看来也并没有说有特别大的需要, 不是吗?

**Comment by nieshuo** [comment]
> 

嗯嗯，确实，我看了下改动需要很多，很费精力，谢谢回答

**Comment by huangjinshe** [comment]
应该也没那么复杂, 你把[OybabServerManager](https://github.com/oybab/TradingSystem/tree/master/TradingSystem/OybabServerManager), [OybabTrans](https://github.com/oybab/TradingSystem/tree/master/TradingSystem/OybabTrans), [OybabServer](https://github.com/oybab/TradingSystem/tree/master/TradingSystem/OybabServer) 这3个项目复制一下每个项目名后面加个Core, 然后把OybabServerCore改造成Asp.Net core为宿主的(目前是用Window服务), 然后移植一下, 相关的库改一下升级一下就可以了. 何不尝试一下呢? 也许成功了直接在Docker里跑多方便.    哦对, [OybabDAL](https://github.com/oybab/TradingSystem/tree/master/TradingSystem/OybabDAL) 可能也要改成Core, 不过目前的Core早就支持EF了, 你应该也可以. 如果你这边没啥问题可以提交个合并, 我再测试看看合并一下就可以了. 可以用VS打开solution后新建一个ServerCore文件夹(原来是Server文件夹)然后把以上新项目都移过去, 又多了一个选择.[手动狗头表情] :-)

**Comment by nieshuo** [comment]
> 

嗯嗯，好~我试试看，谢谢指导

**Comment by githubmyname** [comment]
NET. CORE cross-platform deployment, linux support, do you have plans to refactor?

**Comment by huangjinshe** [comment]
> NET. CORE cross-platform deployment, linux support, do you have plans to refactor?

Maybe in the future. you could try as I mentioned in here:

> 应该也没那么复杂, 你把[OybabServerManager](https://github.com/oybab/TradingSystem/tree/master/TradingSystem/OybabServerManager), [OybabTrans](https://github.com/oybab/TradingSystem/tree/master/TradingSystem/OybabTrans), [OybabServer](https://github.com/oybab/TradingSystem/tree/master/TradingSystem/OybabServer) 这3个项目复制一下每个项目名后面加个Core, 然后把OybabServerCore改造成Asp.Net core为宿主的(目前是用Window服务), 然后移植一下, 相关的库改一下升级一下就可以了. 何不尝试一下呢? 也许成功了直接在Docker里跑多方便. 哦对, [OybabDAL](https://github.com/oybab/TradingSystem/tree/master/TradingSystem/OybabDAL) 可能也要改成Core, 不过目前的Core早就支持EF了, 你应该也可以. 如果你这边没啥问题可以提交个合并, 我再测试看看合并一下就可以了. 可以用VS打开solution后新建一个ServerCore文件夹(原来是Server文件夹)然后把以上新项目都移过去, 又多了一个选择.[手动狗头表情] :-)

**Comment by githubmyname** [comment]
> > NET. CORE cross-platform deployment, linux support, do you have plans to refactor?
> 
> Maybe in the future. you could try as I mentioned in here:
> 
> > 应该也没那么复杂, 你把[OybabServerManager](https://github.com/oybab/TradingSystem/tree/master/TradingSystem/OybabServerManager), [OybabTrans](https://github.com/oybab/TradingSystem/tree/master/TradingSystem/OybabTrans), [OybabServer](https://github.com/oybab/TradingSystem/tree/master/TradingSystem/OybabServer) 这3个项目复制一下每个项目名后面加个Core, 然后把OybabServerCore改造成Asp.Net core为宿主的(目前是用Window服务), 然后移植一下, 相关的库改一下升级一下就可以了. 何不尝试一下呢? 也许成功了直接在Docker里跑多方便. 哦对, [OybabDAL](https://github.com/oybab/TradingSystem/tree/master/TradingSystem/OybabDAL) 可能也要改成Core, 不过目前的Core早就支持EF了, 你应该也可以. 如果你这边没啥问题可以提交个合并, 我再测试看看合并一下就可以了. 可以用VS打开solution后新建一个ServerCore文件夹(原来是Server文件夹)然后把以上新项目都移过去, 又多了一个选择.[手动狗头表情] :-)

Thank you for your reply, very bad, I'm not a developer, hopefully the community is getting better and better, and more people migrate the project.
