### ISSUE TITLE
能正常运行吗

### ISSUE THREAD

**Issue by wanghongwu** [oybab/TradingSystem#3]
怎么搭建开发环境

**Comment by huangjinshe** [comment]
当然. 已经迭代了好几个版本了.

**用户使用:**


1. 到[Release](https://github.com/oybab/TradingSystem/releases)页面下载最新版的安装包. 先安装服务端(`ServerSetup.exe`), 然后安装PC(`PCClientSetup.exe`)或者Tablet(`TabletClientSetup.exe`)版本 (可以和服务端安装到同一个电脑, 如果是局域网用不同电脑安装, 记得确保安装服务端的电脑上的防火墙开启:19998端口)
2. 安装好以后, 打开PC或者Tablet版, 先更改服务器IP. 如果是本地就输入:127.0.0.1 初始账户(管理员:1000 密码:123456).


**开发者使用:**

1. 下载源代码后, 先通过一些Ramdisk工具(可以网上下载免费的)从内存分配一个新硬盘名Y:\盘. (2G就够了). 如果不能, 则需要找到每个项目文件里的`Directory.Build.props`文件, 把里面的路径改为自己电脑上某个固定位置. (使用Ramdisk就是为了让文件生成速度快一些)   (注意:`Directory.Build.props`文件在每个项目文件都有)

![result1](https://user-images.githubusercontent.com/3822799/167083954-bda09271-de51-479c-a150-8dc8ce0b5c0c.png)

![result2](https://user-images.githubusercontent.com/3822799/167083959-a0f2fd6d-27cf-479d-9773-ad6db918ffc1.png)

3. 先用`Visual Studio`打开`TradingSystem\TradingSystem.sln` 之后把`OybabServerConsoleHost`项目设为启动项. 并启动, 这会在本地开启19998端口并模拟服务端.
4. 打开`TradingSystem\TradingSystem.sln`把PC或者Tablet项目设为启动项并进行调试客户端, 或者打开`TradingSystem\TradingSystemX.sln`打开后把UWP,Android,iOS项目设为启动项来进行调试手机客户端. (如果生成时和`OybabServerConsoleHost`冲突, 先把两个项目都生成了再启动`OybabServerConsoleHost`)
5. 调试客户端时, 登录前先更改服务器IP. 如果是本地就输入:127.0.0.1 初始账户(管理员:1000 密码:123456).

**Comment by wanghongwu** [comment]
好的，谢谢你的回复，对这个项目挺感兴趣的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月29日(星期五) 下午3:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [oybab/TradingSystem] 能正常运行吗 (Issue #3)





 
当然. 已经迭代了好几个版本了.
 
用户使用:
  
到Release页面下载最新版的安装包. 先安装服务端(ServerSetup.exe), 然后安装PC(PCClientSetup.exe)或者Tablet(TabletClientSetup.exe)版本 (可以和服务端安装到同一个电脑, 如果是局域网用不同电脑安装, 记得确保安装服务端的电脑上的防火墙开启:19998端口)
 
安装好以后, 打开PC或者Tablet版, 先更改服务器IP. 如果是本地就输入:127.0.0.1  初始账户(管理员:1000 密码:123456).
  
开发者使用:
  
下载源代码后, 先通过一些Ramdisk工具(可以网上下载免费的)从内存分配一个新硬盘名Y:\盘. (2G就够了). 如果不能, 则需要找到每个项目文件里的Directory.Build.props文件, 把里面的路径改为自己电脑上某个固定位置. (使用Ramdisk就是为了让文件生成速度快一些)
 
先用Visual Studio打开TradingSystem\TradingSystem.sln  之后把OybabServerConsoleHost项目设为启动项. 并启动, 这会在本地开启19998端口并模拟服务端.
 
打开TradingSystem\TradingSystem.sln把PC或者Tablet项目设为启动项并进行调试客户端, 或者打开TradingSystem\TradingSystemX.sln打开后把UWP,Android,iOS项目设为启动项来进行调试手机客户端. (如果生成时和OybabServerConsoleHost冲突, 先把两个项目都生成了再启动OybabServerConsoleHost)
 
调试客户端时, 登录前先更改服务器IP. 如果是本地就输入:127.0.0.1  初始账户(管理员:1000 密码:123456).

**Comment by wanghongwu** [comment]
收到，多谢回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月29日(星期五) 下午3:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [oybab/TradingSystem] 能正常运行吗 (Issue #3)





 
当然. 已经迭代了好几个版本了.
 
用户使用:
  
到Release页面下载最新版的安装包. 先安装服务端(ServerSetup.exe), 然后安装PC(PCClientSetup.exe)或者Tablet(TabletClientSetup.exe)版本 (可以和服务端安装到同一个电脑, 如果是局域网用不同电脑安装, 记得确保安装服务端的电脑上的防火墙开启:19998端口)
 
安装好以后, 打开PC或者Tablet版, 先更改服务器IP. 如果是本地就输入:127.0.0.1 初始账户(管理员:1000 密码:123456).
  
开发者使用:
  
下载源代码后, 先通过一些Ramdisk工具(可以网上下载免费的)从内存分配一个新硬盘名Y:\盘. (2G就够了). 如果不能, 则需要找到每个项目文件里的Directory.Build.props文件, 把里面的路径改为自己电脑上某个固定位置. (使用Ramdisk就是为了让文件生成速度快一些)
 
先用Visual Studio打开TradingSystem\TradingSystem.sln 之后把OybabServerConsoleHost项目设为启动项. 并启动, 这会在本地开启19998端口并模拟服务端.
 
打开TradingSystem\TradingSystem.sln把PC或者Tablet项目设为启动项并进行调试客户端, 或者打开TradingSystem\TradingSystemX.sln打开后把UWP,Android,iOS项目设为启动项来进行调试手机客户端. (如果生成时和OybabServerConsoleHost冲突, 先把两个项目都生成了再启动OybabServerConsoleHost)
 
调试客户端时, 登录前先更改服务器IP. 如果是本地就输入:127.0.0.1 初始账户(管理员:1000 密码:123456).

**Comment by huangjinshe** [comment]
别客气.   对了, 手机版的话你可以在`App Store`或者其他应用市场搜索一下: `梦胜交易系统`  或 `Oybab Trading`. 不过手机版页面并没有过多的去设计, 太普通了. 反正`Xamarin`寿命也不多. 也许未来`MAUI`发布时再移植过去并重新设计手机版UI吧.

**Comment by xklake** [comment]
运行不了，而且看起来很多的核心代码没有开源。

**Comment by wanghongwu** [comment]
啥开发环境，我还没试过？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Qiang ***@***.***&gt;; 
发送时间: 2022年5月5日(星期四) 下午5:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [oybab/TradingSystem] 能正常运行吗 (Issue #3)





 
运行不了，而且看起来很多的核心代码没有开源。

**Comment by huangjinshe** [comment]
> 运行不了，而且看起来很多的核心代码没有开源。

别误人子弟行吗? 有什么问题直接提交一个新的Issue, 我相信能帮你解决. 都几年的项目了, 怎么可能运行不了.

另外你说的核心代码没有开源, 也麻烦你提交一个新的Issue来说明一下, 我倒是看看哪个代码你没看到. (如果第三方组件, 请你自己找相关代码, 不过所有这个项目有关的一切核心都已经开源了.)

**Comment by xklake** [comment]
> > 运行不了，而且看起来很多的核心代码没有开源。
> 
> 别误人子弟行吗? 有什么问题直接提交一个新的Issue, 我相信能帮你解决. 都几年的项目了, 怎么可能运行不了.
> 
> 另外你说的核心代码没有开源, 也麻烦你提交一个新的Issue来说明一下, 我倒是看看哪个代码你没看到. (如果第三方组件, 请你自己找相关代码, 不过所有这个项目有关的一切核心都已经开源了.)

如果有冒犯请原谅。
我也只是随便看一下，android里面的views的代码看不到，还有几个三方库找不到导致无法编译成功，等我多花点时间仔细研究一下再来报告。谢谢。

**Comment by huangjinshe** [comment]
> > > 运行不了，而且看起来很多的核心代码没有开源。
> > 
> > 
> > 别误人子弟行吗? 有什么问题直接提交一个新的Issue, 我相信能帮你解决. 都几年的项目了, 怎么可能运行不了.
> > 另外你说的核心代码没有开源, 也麻烦你提交一个新的Issue来说明一下, 我倒是看看哪个代码你没看到. (如果第三方组件, 请你自己找相关代码, 不过所有这个项目有关的一切核心都已经开源了.)
> 
> 如果有冒犯请原谅。 我也只是随便看一下，android里面的views的代码看不到，还有几个三方库找不到导致无法编译成功，等我多花点时间仔细研究一下再来报告。谢谢。

好的, 没问题.    记得还原一下Nuget包, 另外有问题随时新开一个Issue, 一定帮你解决.

**Comment by wanghongwu** [comment]
[运行不起来](https://cdn.jsdelivr.net/gh/wanghongwu/myphotos@master/20220506/QQ截图20220506141832.47v4qli1sri0.webp)
感觉搭建开发环境有点难

**Comment by wanghongwu** [comment]
[运行不起来](https://cdn.jsdelivr.net/gh/wanghongwu/myphotos@master/20220506/QQ截图20220506141832.47v4qli1sri0.webp)
感觉搭建开发环境有点难

**Comment by huangjinshe** [comment]
@wanghongwu , 你有按照我上面说的做了吗? 把所有项目里 `Directory.Build.props` 文件里的路径改为某个你硬盘绝对路径??

![result1](https://user-images.githubusercontent.com/3822799/167083954-bda09271-de51-479c-a150-8dc8ce0b5c0c.png)

![result2](https://user-images.githubusercontent.com/3822799/167083959-a0f2fd6d-27cf-479d-9773-ad6db918ffc1.png)


如果这个做到了, 再成功恢复了Nuget包, 我觉得就没什么问题. 真的一点都不难, 有问题你就说, 我这边帮你.

**Comment by wanghongwu** [comment]
平时用php开发，对C#不熟悉有时间再弄了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月6日(星期五) 下午3:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [oybab/TradingSystem] 能正常运行吗 (Issue #3)





 
@wanghongwu , 你有按照我上面说的做了吗? 把 Directory.Build.props 里的路径改为某个你硬盘绝对路径??
 
如果这个做到了, 再成功恢复了Nuget包, 我觉得就没什么问题. 真的一点都不难, 有问题你就说, 我这边帮你.

**Comment by huangjinshe** [comment]
可以. 图片也已经给你上传了.  记得至少下载 Visual Studio 2019

**Comment by wanghongwu** [comment]
怎么恢复Nuget包 我这边还很多错的[](https://cdn.jsdelivr.net/gh/wanghongwu/myphotos@master/20220506/QQ截图20220506151707.4hde4p1z9xm0.webp)

**Comment by wanghongwu** [comment]
怎么恢复Nuget包 我这边还很多错的[截图](https://cdn.jsdelivr.net/gh/wanghongwu/myphotos@master/20220506/QQ截图20220506151707.4hde4p1z9xm0.webp)

**Comment by huangjinshe** [comment]
注意:`Directory.Build.props`文件在每个项目文件都有, 不是只有一个.  你先把他们路径都改好了, 关闭Visual Studio 2010, 并重新打开. 默认情况下Nuget包会在生成前自动恢复.  如果没有, 你可以尝试: 在解决方案(不是项目, 是最顶部的解决方案)名称上点右键，选择"启用NuGet程序包还原"

**Comment by huangjinshe** [comment]
你先起码把PC客户端成功运行一下试试.  Android项目和iOS项目都需要响应的东西. Android需要下载SDK和模拟器(你有没有做过Android开发), iOS更是需要连接一台Mac笔记本.

**Comment by wanghongwu** [comment]
我用就是Y盘




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月6日(星期五) 下午3:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [oybab/TradingSystem] 能正常运行吗 (Issue #3)





 
你先起码把PC客户端成功运行一下试试.  Android项目和iOS项目都需要响应的东西. Android需要下载SDK和模拟器(你有没有做过Android开发), iOS更是需要连接一台Mac笔记本.

**Comment by huangjinshe** [comment]
那就是需要考虑还原Nuget包. 和安卓SDK有关的操作了.  还原Nuget包, 网上搜索一下应该有带图片解释如何操作.

**Comment by wanghongwu** [comment]
好的
